### ISSUE TITLE
Thanks! small typo!

### ISSUE THREAD

**Issue by ftlno** [half-cambodian-hacker-man/qmk-hs60v3iso-half-kh-hacker#1]
Hi, thanks for the awesome example. trying to use it now. Just wanted to let you know that you write different guides here and at https://anthony.som.codes/blog/2020-02-01-qmk-reactive-rgb/

`#include "../hs60/v2/iso/keymaps/half-kh-hacker/backlighting/user_bl.h"`
vs
`+#include "../hs60/v2/iso/keymaps/half-kh-hacker/backlighting.h"`

👍

**Comment by ftlno** [comment]
Got it to work, but ended up modding the via keycap! Thanks again! :D

**Comment by char** [comment]
That's just because this repo's file structure has changed since I wrote the post - This is the actual keymap I use on a day-to-day basis, rather than a guide, so it's subject to change.
